### PR TITLE
added working flatpak manifest

### PR DESCRIPTION
**Pull request by GabMus**
Should solve #99.

I added a very simple flatpak manifest that includes mednafen, I tested it with a couple of gba games and it works. Feel free to ask any questions or tell me if I missed anything relevant.

### CODE REVIEW

**Comment by anthonyajumelles** [comment]
I don't think @AmatCoder uses the site very frequently so they may not see this for quite some time. 

Probably best to submit to Flathub independently for the time being.

**Comment by AmatCoder** [comment]
@anthonyajumelles
I asked for permission from mednafen authors [here](https://forum.fobby.net/index.php?t=msg&th=1999&#msg_6440).

If it is accepted, I might have some time to do this next week.

**Comment by GabMus** [comment]
Great, thanks for the feedback.

I don't use Mednaffe myself and found this issue on bountysource for 5 bucks, so I just thought I could give you a hand and get a pizza in return.

I will make the appropriate changes and make an additional commit. I just have one small concern, regarding home access: typically you would want to use `~/.local/share/mednafen` and `~/.config/mednafen` for storing data in the user's home directory, it'd probably be best to use those.

Additionally, if you/we try to get this app on flathub, they typically point out that writing configs and other data outside of the flatpak sandbox is generally discouraged, so maybe the best option here would be to keep the home access read only to load ROMs and other relevant files, as well as properly migrate `MEDNAFEN_HOME` to a flatpak-aware location (simply put, if the app is running inside a flatpak sandbox, set use this path, else this other path).

**Comment by GabMus** [comment]
Using the freedesktop runtime results in a missing icon and different font compared to the system default. Any particular reason why you don't want to use the gnome runtime? Besides, for GTK applications I think it makes sense to use it.

**Comment by AmatCoder** [comment]
@GabMus
I am testing this and:

- No missing icons here using the freedesktop runtime and default theme. So that must be a problem with your theme.
- It needs _"--device=all"_ for controllers.
- Also it needs _"--share=network"_ for netplay.
- Also it needs read/write full access to the user’s home directory because mednafen allows you to set the paths to directories for save states, screenshots, etc.

So my proposal would be as follows:

    {
    "app-id": "com.github.mednaffe",
    "command": "mednaffe",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "20.08",
    "sdk": "org.freedesktop.Sdk",
    "finish-args": [
        "--share=network",
        "--share=ipc",
        "--socket=fallback-x11",
        "--socket=wayland",
        "--socket=pulseaudio",
        "--device=all",
        "--filesystem=home"
    ],
    "modules": [
        {
            "name": "mednafen",
            "buildsystem": "autotools",
            "sources": [
                {
                    "type": "archive",
                    "url": "https://mednafen.github.io/releases/files/mednafen-1.26.1.tar.xz",
                    "sha256": "842907c25c4292c9ba497c9cb9229c7d10e04e22cb4740d154ab690e6587fdf4"
                }
            ]
        },
        {
            "name": "mednaffe",
            "buildsystem": "autotools",
            "sources": [
                {
                    "type": "archive",
                    "url": "https://github.com/AmatCoder/mednaffe/releases/download/0.9.1/mednaffe-0.9.1.tar.gz",
                    "sha256": "426cd53342db9f6d619f5b7fafda3a262e5b4789aa87790265bb09ce674b454f"
                }
            ]
        }
    ]
    }

**Comment by GabMus** [comment]
Updated the manifest, still have the missing icon, even after switching to Adwaita (I was using Adwaita-dark before), but I guess it's just a problem with my system if you have it working. Let me know if it can be merged

**Comment by AmatCoder** [comment]
Do you mean to merging to the mednaffe repository? If so, yes, it can be merged right now.

If you mean to merging to flathub then we will have to wait (I am writing a AppData file).

**Comment by GabMus** [comment]
> Do you mean to merging to the mednaffe repository? If so, yes, it can be merged right now.
> 
> If you mean to merging to flathub then we will have to wait (I am writing a AppData file).

I mean in the mednaffe repo. It makes sense to include the manifest in the app repo, so that you can track it along with the code, and it makes it easier for third parties to help with development,. as they can just open the repo in gnome builder and press play.

Feel free to merge if you think it's ready! Also, if you need any help with the appdata file, feel free to ask!

**Comment by AmatCoder** [comment]
Merged. Thanks for your work!

**Comment by GabMus** [comment]
Thank you for making Mednaffe! Next steps would be:

1. Add a CI pipeline that automatically builds a flatpak with every ~~commit~~ push (this is way easier on gitlab, but I can look into it)
2. Submit to flathub!

**Pull request merged**
